# Simple Image Compression Test
We wish to test our FHE system with something easy, 2x image size reduction with grayscale images. To do this we will allow the user to input an image, compress it to 16 by 16 grayscale, and then pass it off to our server to get a response of a 8 by 8 grayscale image.

In [12]:
import cv2
import numpy as np
import random
from matplotlib import pyplot as plt

%matplotlib inline

DEFAULT_WIDTH = 16
DEFAULT_HEIGHT = 16

TEST_IMAGE = 'kung.jpg'

In [13]:
"""
Resizes an image to 16x16 and then convert to
grayscale for testing FHE resize on simple example
"""
def prepare_image(imname, dim=(DEFAULT_WIDTH, DEFAULT_HEIGHT)):
    image = cv2.imread(imname)
    image = cv2.resize(image, dim)
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    #plt.imshow(gray_image, cmap='gray')
    return gray_image

In [14]:
"""
Prints an image to a file in a specific format
Width
Height
im[0][0]
im[0][1]  
...
There should be Width*Height+2 lines in total
"""
def prepare_file(image, fname):
    h, w = image.shape
    outfile = open(fname, 'w+')
    outfile.write(str(h))
    outfile.write("\n")
    outfile.write(str(w))
    outfile.write("\n")
    for row in image:
        for el in row:
            outfile.write(str(el))
            outfile.write("\n")
    outfile.close()
    


In [15]:
im = prepare_image(TEST_IMAGE)
print(im)

[[174 177 184 191 196 200 200 204 207 210 211 213 213 214 215 216]
 [184 189 194 199 206 208 129  27  36  15  19  77 224 219 223 224]
 [192 195 201 203 217  34  23  15  13  15  15  29  43 151 230 232]
 [201 205 207 215  53  38  30  17  18  16  53  51  18  56 201 238]
 [208 211 211  79  74  83  49  20  40 127 142 117  93  30  29 242]
 [216 219 216  51  81  95  84  47 144 157 153 136 106  26  48 241]
 [221 222 222  45 165 181 178 184 188 173 155 132 114  42  50 241]
 [221 223 227  25  66 160 181 181 166 178 142  87 115  40  26 245]
 [223 224 225  31 127 128 103 167 141 116 134 103 124  50  48 246]
 [225 225 226 200 167 154 149 150 139 145 133 139 135 118  87 243]
 [228 226 226 235 168 165 164 198 134  98 169 154 130 132 247 242]
 [228 227 227 232 152 173 151 150 141 121 170 135 117  88 240 242]
 [224 227 228 231 156 162  89 242 197  54 157 153 114 218 239 239]
 [219 222 224 232 237 154 149 146 130 130 141 142 122 212 237 237]
 [220 217 218 224 223 222 160 162 156 156 127 108 208 220 220 

In [11]:
prepare_file(im, 'kung.txt')